using { com.logaligroup as entities } from '../db/schema';
using {API_BUSINESS_PARTNER as bp} from './external/API_BUSINESS_PARTNER';

service Header {
    type form {
        foption : String(10);
        famount : Integer;
    }

  entity Header  as projection on entities.Header ;
  entity Items   as projection on entities.Items;
  entity Reviews as projection on entities.Reviews;

    entity Inventories      as projection on entities.Inventories
        actions {
     /*       @Core.OperationAvailable: {
                $edmJson: {
                    $If: [
                        {
                            $Eq: [
                                {
                                    $Path: 'in/Header/IsActiveEntity'
                                },
                                true
                            ]
                        },
                        true,
                        false
                    ]
                }
            } */
            @Common : { 
                SideEffects : {
                    $Type : 'Common.SideEffectsType',
                    TargetProperties : [
                        'in/quantity',
                    ],
                    TargetEntities : [
                        in.Header
                    ],
                },
            } 
            action setStock(
                            in : $self,
                            option: form:foption,
                            amount: form:famount
             )
        };

    entity Sales as projection on entities.Sales;


//-------------------------------------
  /** ValueHelps -  */
  @readonly
  entity VH_Status as projection on entities.Status;

    @readonly
    entity VH_Options       as projection on entities.Options;

    /** Services OData - Remote */

    @readonly
    entity VH_Supplier as projection on bp.A_Supplier {
        key Supplier,
            SupplierFullName as FullName,
            SupplierName
    };

}